<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5350ed8d-f5b6-4101-8087-bb92dc6b1fce</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Carter" Version="9.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.4" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
    <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Decofleet.Application\Decofleet.Application.csproj" />
    <ProjectReference Include="..\Decofleet.Infrastructure\Decofleet.Infrastructure.csproj" />
    <ProjectReference Include="..\Decofleet.Contracts\Decofleet.Contracts.csproj" />
  </ItemGroup>
</Project>
